services:
  media-management:
    container_name: media-management
    environment:
      - TZ=Asia/Shanghai
    image: kenny2023/media-management:latest
    pull_policy: always
    ports:
      - '38000:8000'
    restart: unless-stopped
    volumes:
      - /mnt/Pool_SH/Application/media-management/storage:/app/storage
version: '3.9'
